analyzer:
  errors:
    avoid_print: ignore
    constant_identifier_names: ignore
    library_private_types_in_public_api: ignore
include: package:flutter_lints/flutter.yaml
linter:
  rules:
    - annotate_overrides
    - hash_and_equals
    - prefer_is_not_empty
