name: techshop_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  animated_notch_bottom_bar: ^1.0.3
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cool_alert: ^2.0.1
  device_info_plus: ^9.1.0
  dio: ^5.4.3+1
  fluentui_system_icons: ^1.1.246
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_slidable: ^3.1.0
  flutter_spinkit: ^5.2.1
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  import_sorter: ^4.6.0
  intl: ^0.18.0
  loading_animation_widget: ^1.2.0+4
  lottie: ^2.2.0
  pattern_formatter: ^3.0.0
  permission_handler: ^11.0.1
  pretty_dio_logger: ^1.3.1
  qr_flutter: ^4.1.0
  screenshot: ^3.0.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  skeletonizer: ^1.3.0
  timelines: ^0.1.0
  uni_links: ^0.5.1
  url_launcher: ^6.2.1
  url_strategy: ^0.2.0
  webview_flutter: ^4.0.5

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/Order/
    - assets/images/Cart/
    - assets/files/
