name: techshop_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_slidable: ^3.1.0
  flutter_spinkit: ^5.2.1
  get: ^4.6.6
  intl: ^0.18.0
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.3
  timelines: ^0.1.0
  uni_links: ^0.5.1
  url_launcher: ^6.2.1
  webview_flutter: ^4.0.5
  loading_animation_widget: ^1.2.0+4
  image_gallery_saver: ^2.0.3
  device_info_plus: ^9.1.0
  permission_handler: ^11.0.1
  screenshot: ^3.0.0
  qr_flutter: ^4.1.0
  pattern_formatter: ^3.0.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/Order/
    - assets/images/Cart/
    - assets/files/
